
export const projectInfo = [
    {
        id: 1,
        name: "PCK",
        date: "2023",
        icons: ["html", "css", "javascript", "gsap"],
        review:
            "Landing page for a donation platform with smooth GSAP animations and a step-by-step donation flow.",
        images: "pck",
        bgColor: "bg-yellow-300/60",
        bgColor2: "bg-black",
        textColor: "text-black",
        textColor2: "text-white",
        href: "https://pck-fundation.netlify.app",
        gitHref: "https://github.com/Xebec13/PCK-Zbiorka",
    },
    {
        id: 2,
        name: "Afal-Logistics",
        date: "2024",
        icons: ["html", "css", "javascript", "gsap"],
        review:
            "Single page MVP application prepared for a local logistics company, aimed at building brand recognition for potential customers.",
        images: "afal",
        bgColor: "bg-black/50",
        bgColor2: "bg-red-400/80",
        textColor: "text-white",
        textColor2: "text-black",
        href: "https://afal-logistics.netlify.app",
        gitHref: "https://github.com/Xebec13/Afal-Logistics",
    },
    {
        id: 3,
        name: "Chat-GPT3 Landing Page",
        date: "2024",
        icons: ["react", "css", "javascript", "gsap"],
        review:
            "Simple and clear landing page showcasing AI product features with responsive layout.",
        images: "chatgpt",
        bgColor: "bg-indigo-400/20",
        bgColor2: "bg-sky-400/80",
        textColor: "text-white",
        textColor2: "text-black",
        href: "https://what-chat-gpt3.netlify.app",
        gitHref: "https://github.com/Xebec13/Chat-GPT3",
    },
    {
        id: 4,
        name: "Gericht Restaurant",
        date: "2024",
        icons: ["react", "css", "javascript", "gsap"],
        review:
            "Landing page for a modern restaurant brand, later improved with GSAP animations for interactivity.",
        images: "gericht",
        bgColor: "bg-amber-300/40",
        bgColor2: "bg-black/80",
        textColor: "text-black",
        textColor2: "text-amber-300",
        href: "https://grestaurant-landing-page.netlify.app",
        gitHref: "https://github.com/Xebec13/Gericht-Restaurant",
    },
    {
        id: 5,
        name: "Cozy Leaf",
        date: "2025",
        icons: ["react", "tailwind", "javascript", "gsap"],
        review:
            "Modern restaurant website with responsive design, smooth GSAP animations, and SEO optimization.",
        images: "cozy",
        bgColor: "bg-pink-500/40",
        bgColor2: "bg-green-500/80",
        textColor: "text-violet-100",
        textColor2: "text-fuchsia-100",
        href: "https://cl-restaurant.netlify.app",
        gitHref: "https://github.com/Xebec13/Cozy-Leaf",
    },
    // {
    //   id: 6,
    //   name: "Post Prime",
    //   date: "2025",
    //   icons: ["react", "sass", "javascript", "gsap"],
    //   review:
    //     "Post Prime is a sleek podcast site for former basketball players, featuring smooth content delivery and an appealing interface tailored to sports enthusiasts.",
    //   images: [cl1, cl1, cl1], // ⚠️ placeholders
    //   bgColor: "bg-gray-300/40",
    //   bgColor2: "bg-cyan-300",
    //   textColor: "text-black",
    //   textColor2: "text-cyan-900",
    //   href: "#",
    //   gitHref: "https://github.com/TwojNick/post-prime",
    // },
];